### ISSUE TITLE
Signature, confusion avec le bouton document

### ISSUE THREAD

**Issue by lmag** [Evarisk/Saturne#650]
Téléchargement du document à signer

![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/c8f9a219-8881-4c9d-8821-bff80b121aa1)

à refaire
![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/213e039c-cfc6-4abd-ac08-c035e7b8da06)

**Comment by lmag** [comment]
1 seule interface en 3 étapes
![image](https://github.com/Evarisk/Saturne/assets/3288514/1727f060-dbe0-4ff6-badb-d9a1ef4d9437)

**Comment by eoxia-amandine** [comment]
Etape 1
![signature](https://github.com/Evarisk/Saturne/assets/18576747/e8363b15-9e63-4184-909a-98fba283589d)

Etape 2
![signature-valide](https://github.com/Evarisk/Saturne/assets/18576747/b19e0c7c-b4b8-40a9-bd9b-0545e707c67c)

**Comment by lmag** [comment]
Ouah !!!!!!!! Trop bien peux tu faire la version mobile ? @eoxia-amandine

**Comment by nicolas-eoxia** [comment]
2 problèmes : 

- [ ] le bouton retour doit être gérer indépendamment du header informations et header object pour gérer un navigation et conserver une cohérence dans l'affichage.
- [ ] le logo n'est pas centré par rapport au centre de l'image du coup c'est décaler vers la droite
@eoxia-amandine à toi de jouer

![Image](https://github.com/Evarisk/Saturne/assets/52404047/16f11ffb-a2b2-44ad-8406-94d822e0fc29)
