### ISSUE TITLE
Bug 19

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/Saturne#863]
il faut détyper $version dans les fichiers doc_ ... et peut être ailleurs
il faut gérer les cas de la nouvelle Exception OdfExceptionSegmentNotFound dans la fonction fillTagsLines et surement ailleurs

**Comment by evarisk-charles** [comment]
![Image](https://github.com/Evarisk/Saturne/assets/158461084/be5ac903-f740-40a4-8a2c-464dc6f7ef89)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/6446c75e-ddbb-44bc-8225-cd509a64809d)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/ab464f3c-6244-4589-87d8-606af799b34f)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/579305f2-a2bb-4d7f-84f8-2348438d208c)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/35720caa-8115-43f7-9377-bd4844c770c8)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/e19d5018-3e24-4936-982b-727f03f1a0ea)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/0256eb82-56fc-4976-b3fc-bcd9d0c2a86e)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/a3826abb-d24d-41e2-bf72-c9735bd02916)



![Image](https://github.com/Evarisk/Saturne/assets/158461084/6f9a26ec-9344-4261-8215-37a9ff49d8ac)

**Comment by nicolas-eoxia** [comment]
https://github.com/Dolibarr/dolibarr/pull/29027 : PR Dolibarr pour fix le bug sur les select
